### ISSUE TITLE
Failed to deserialize the plugin manifest retrieved from "https://github.com/arition/jellyfin-plugin-ignore"

### ISSUE THREAD

**Issue by eujanro** [arition/jellyfin-plugin-ignore#1]
Hi arition,
great ideea to develop such a plugin.
I just tried to install it, but the logs are returning the following error on Plugin uptades:

---------------
[2022-11-03 16:03:58.083 +01:00] [INF] [13] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2022-11-03 16:03:58.086 +01:00] [INF] [13] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "PluginUpdateTask"
[2022-11-03 16:03:58.088 +01:00] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2022-11-03 16:03:59.442 +01:00] [ERR] [16] Emby.Server.Implementations.Updates.InstallationManager: Failed to deserialize the plugin manifest retrieved from "https://github.com/arition/jellyfin-plugin-ignore"
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 7 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 7 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)
[2022-11-03 16:03:59.460 +01:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 1 seconds

---------------

My system
JF Version: 10.8.7
Operating System: Windows
Architecture: X64

Perhaps you could understand better why is not working.
I'm not a developer, but I'm glad to help

**Comment by arition** [comment]
Hi, the plugin does not have a repo, so you need to install it manually.

Please download the zip from release section and install it to the plugin folder.

https://jellyfin.org/docs/general/server/plugins/index.html#manual

**Comment by hugalafutro** [comment]
Hi, how would I do this if my jellyfin is in docker? Thanks!

**Comment by arition** [comment]
I do not use docker for jellyfin. I guess you can check https://www.reddit.com/r/jellyfin/comments/kp50m6/plugin_dll_installation_on_docker_install/ or just search related info.
